name: Go
on: [push]
jobs:

  test_and_build:
    name: Test
    runs-on: ubuntu-latest
    steps:
  
    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
  
    - name: Setup go
      uses: actions/setup-go@v1
      with:
        go-version: '1.13'

    - name: Test
      run: make test

    - name: Build
      run: make

    - name: Archive production artifacts
      uses: actions/upload-artifact@v1
      with:
        name: dist
        path: dist
